# coding: utf-8

"""
    Library System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_add_book_books_post(self) -> None:
        """Test case for add_book_books_post

        Add Book
        """
        pass

    def test_cancel_reservation_reservations_reservation_id_delete(self) -> None:
        """Test case for cancel_reservation_reservations_reservation_id_delete

        Cancel Reservation
        """
        pass

    def test_get_books_books_get(self) -> None:
        """Test case for get_books_books_get

        Get Books
        """
        pass

    def test_reserve_book_books_book_id_reserve_post(self) -> None:
        """Test case for reserve_book_books_book_id_reserve_post

        Reserve Book
        """
        pass


if __name__ == '__main__':
    unittest.main()
